### ISSUE TITLE
Some problems arising during first tests on the tripod motion control 

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#5]
After the preliminary tests we ran to check the control of the tripod we can report on the following problems we need to address:
- [x] `yarpmotorgui` needs to be extended to expose fractional slider steps (see https://github.com/robotology/yarp/issues/628).
- `solver` related bugs/improvements:
  - [x] the state port streams out the `pitch` and the `roll` in radians instead of degrees (fixed via https://github.com/robotology/cer/commit/641bb41b826e95be73e42597eaa04b517ef9a41c).
  - [x] account for the roto-translation matrix `T0` (addressed via #6).
- `tripodMotionControl` related bugs/improvements:
  - [x] handle a configurable `T0` (via https://github.com/robotology/cer/commit/f500cc7747b48eca20368e4416e76af6b6d63100).
  - [x] compute proper speed on the fly for each joint so that the joints will attain the desired targets at the same time.
  - [x] `seg-fault` caught when cleaning memory at shut-down (fixed via https://github.com/robotology/cer/commit/392603324ff35fef113fbef51b0dbd7a6b982e3d).
- `FW` related bugs/improvements:
  - [x] we have to make sure that both the `FW` and the `solver` will use the same structure's bounds ([**`done`**](https://github.com/robotology/cer/issues/5#issuecomment-152258922)).
  - [x] the `FW` gets somehow stuck when an angular limit is reached ([**`fixed`**](https://github.com/robotology/cer/issues/5#issuecomment-152256806)).
  - [x] calibration of the torso (see https://github.com/robotology/icub-firmware/issues/25 [**`done`**](https://github.com/robotology/icub-firmware/commit/67520b11d9b297a7e21c16ae090c90d2ed61d597)).
  - [x] when the low-level limit checker kicks in stopping the motion of the tripod, we agreed to make the desired set-points equal to the current encoders values  (fixed via https://github.com/robotology/icub-firmware/commit/d6ffe3a8399ea4ff6b70a99343008c7b7caedd8f).

These are all minor bugs/improvements since we were happy to see the tripod moving correctly in most configurations.

/cc @ale-git @barbalberto @randaz81

**Comment by ale-git** [comment]
Fixed low level tilt limit stuck bug by https://github.com/robotology/icub-firmware/commit/1eb755bff1ab7a2972f9bf9cb7fb03e9477b5e09

**Comment by ale-git** [comment]
The high level tilt limit has been deacreased to 25 degrees, the same in the low level control. 25 degrees is close to the mechanical limit.

**Comment by pattacini** [comment]
:+1:

**Comment by pattacini** [comment]
@barbalberto could we imagine to try to meet the _on-the-fly speed computation_ requirement by tomorrow morning so that we can run a further test before the meeting?

**Comment by barbalberto** [comment]
I'll start working on it right now

**Comment by pattacini** [comment]
Great! :+1:

**Comment by barbalberto** [comment]
Commits done!
Let's meet monday morning to re-test everything!!!

@ale-git @pattacini

**Comment by pattacini** [comment]
@barbalberto is the `seg-fault` fixed?

**Comment by barbalberto** [comment]
On my laptop yes, final word on this to @ale-git

**Comment by ale-git** [comment]
I haven't seen seg-faults any more after the fix.

**Comment by pattacini** [comment]
:+1: 
Let's tick this as fixed then.

**Comment by pattacini** [comment]
Hi @ale-git 
We've identified two new points (I've reported in the first post) we have to go through before considering the deadline met. Could you work on these?

**Comment by ale-git** [comment]
The setpoint issue is fixed, the calibration requires a little more time, I'll manage to close it today anyway.

**Comment by pattacini** [comment]
Great! Thanks.

**Comment by pattacini** [comment]
The latest `yarpmotorgui` is under test (see https://github.com/robotology/yarp/issues/628) but it already implements the fractional step sliders in a dedicated branch, which is waiting to be merged into master.

All the other issues have been addressed successfully, closing...
